/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  FacilityAdmin as PrismaFacilityAdmin,
  Facility as PrismaFacility,
} from "@prisma/client";

export class FacilityAdminServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.FacilityAdminCountArgs, "select">
  ): Promise<number> {
    return this.prisma.facilityAdmin.count(args);
  }

  async facilityAdmins(
    args: Prisma.FacilityAdminFindManyArgs
  ): Promise<PrismaFacilityAdmin[]> {
    return this.prisma.facilityAdmin.findMany(args);
  }
  async facilityAdmin(
    args: Prisma.FacilityAdminFindUniqueArgs
  ): Promise<PrismaFacilityAdmin | null> {
    return this.prisma.facilityAdmin.findUnique(args);
  }
  async createFacilityAdmin(
    args: Prisma.FacilityAdminCreateArgs
  ): Promise<PrismaFacilityAdmin> {
    return this.prisma.facilityAdmin.create(args);
  }
  async updateFacilityAdmin(
    args: Prisma.FacilityAdminUpdateArgs
  ): Promise<PrismaFacilityAdmin> {
    return this.prisma.facilityAdmin.update(args);
  }
  async deleteFacilityAdmin(
    args: Prisma.FacilityAdminDeleteArgs
  ): Promise<PrismaFacilityAdmin> {
    return this.prisma.facilityAdmin.delete(args);
  }

  async findFacilities(
    parentId: string,
    args: Prisma.FacilityFindManyArgs
  ): Promise<PrismaFacility[]> {
    return this.prisma.facilityAdmin
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .facilities(args);
  }
}
