/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { FacilityAdminService } from "../facilityAdmin.service";
import { FacilityAdminCreateInput } from "./FacilityAdminCreateInput";
import { FacilityAdmin } from "./FacilityAdmin";
import { FacilityAdminFindManyArgs } from "./FacilityAdminFindManyArgs";
import { FacilityAdminWhereUniqueInput } from "./FacilityAdminWhereUniqueInput";
import { FacilityAdminUpdateInput } from "./FacilityAdminUpdateInput";
import { FacilityFindManyArgs } from "../../facility/base/FacilityFindManyArgs";
import { Facility } from "../../facility/base/Facility";
import { FacilityWhereUniqueInput } from "../../facility/base/FacilityWhereUniqueInput";

export class FacilityAdminControllerBase {
  constructor(protected readonly service: FacilityAdminService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: FacilityAdmin })
  async createFacilityAdmin(
    @common.Body() data: FacilityAdminCreateInput
  ): Promise<FacilityAdmin> {
    return await this.service.createFacilityAdmin({
      data: data,
      select: {
        createdAt: true,
        email: true,
        employeeId: true,
        firstName: true,
        id: true,
        lastName: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [FacilityAdmin] })
  @ApiNestedQuery(FacilityAdminFindManyArgs)
  async facilityAdmins(
    @common.Req() request: Request
  ): Promise<FacilityAdmin[]> {
    const args = plainToClass(FacilityAdminFindManyArgs, request.query);
    return this.service.facilityAdmins({
      ...args,
      select: {
        createdAt: true,
        email: true,
        employeeId: true,
        firstName: true,
        id: true,
        lastName: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: FacilityAdmin })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async facilityAdmin(
    @common.Param() params: FacilityAdminWhereUniqueInput
  ): Promise<FacilityAdmin | null> {
    const result = await this.service.facilityAdmin({
      where: params,
      select: {
        createdAt: true,
        email: true,
        employeeId: true,
        firstName: true,
        id: true,
        lastName: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: FacilityAdmin })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateFacilityAdmin(
    @common.Param() params: FacilityAdminWhereUniqueInput,
    @common.Body() data: FacilityAdminUpdateInput
  ): Promise<FacilityAdmin | null> {
    try {
      return await this.service.updateFacilityAdmin({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          employeeId: true,
          firstName: true,
          id: true,
          lastName: true,
          phoneNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: FacilityAdmin })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteFacilityAdmin(
    @common.Param() params: FacilityAdminWhereUniqueInput
  ): Promise<FacilityAdmin | null> {
    try {
      return await this.service.deleteFacilityAdmin({
        where: params,
        select: {
          createdAt: true,
          email: true,
          employeeId: true,
          firstName: true,
          id: true,
          lastName: true,
          phoneNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/facilities")
  @ApiNestedQuery(FacilityFindManyArgs)
  async findFacilities(
    @common.Req() request: Request,
    @common.Param() params: FacilityAdminWhereUniqueInput
  ): Promise<Facility[]> {
    const query = plainToClass(FacilityFindManyArgs, request.query);
    const results = await this.service.findFacilities(params.id, {
      ...query,
      select: {
        accountant: {
          select: {
            id: true,
          },
        },

        address: true,
        contactNumber: true,
        createdAt: true,

        doctor: {
          select: {
            id: true,
          },
        },

        facilityAdmin: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/facilities")
  async connectFacilities(
    @common.Param() params: FacilityAdminWhereUniqueInput,
    @common.Body() body: FacilityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      facilities: {
        connect: body,
      },
    };
    await this.service.updateFacilityAdmin({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/facilities")
  async updateFacilities(
    @common.Param() params: FacilityAdminWhereUniqueInput,
    @common.Body() body: FacilityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      facilities: {
        set: body,
      },
    };
    await this.service.updateFacilityAdmin({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/facilities")
  async disconnectFacilities(
    @common.Param() params: FacilityAdminWhereUniqueInput,
    @common.Body() body: FacilityWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      facilities: {
        disconnect: body,
      },
    };
    await this.service.updateFacilityAdmin({
      where: params,
      data,
      select: { id: true },
    });
  }
}
