/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { FacilityAdmin } from "./FacilityAdmin";
import { FacilityAdminCountArgs } from "./FacilityAdminCountArgs";
import { FacilityAdminFindManyArgs } from "./FacilityAdminFindManyArgs";
import { FacilityAdminFindUniqueArgs } from "./FacilityAdminFindUniqueArgs";
import { CreateFacilityAdminArgs } from "./CreateFacilityAdminArgs";
import { UpdateFacilityAdminArgs } from "./UpdateFacilityAdminArgs";
import { DeleteFacilityAdminArgs } from "./DeleteFacilityAdminArgs";
import { FacilityFindManyArgs } from "../../facility/base/FacilityFindManyArgs";
import { Facility } from "../../facility/base/Facility";
import { FacilityAdminService } from "../facilityAdmin.service";
@graphql.Resolver(() => FacilityAdmin)
export class FacilityAdminResolverBase {
  constructor(protected readonly service: FacilityAdminService) {}

  async _facilityAdminsMeta(
    @graphql.Args() args: FacilityAdminCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [FacilityAdmin])
  async facilityAdmins(
    @graphql.Args() args: FacilityAdminFindManyArgs
  ): Promise<FacilityAdmin[]> {
    return this.service.facilityAdmins(args);
  }

  @graphql.Query(() => FacilityAdmin, { nullable: true })
  async facilityAdmin(
    @graphql.Args() args: FacilityAdminFindUniqueArgs
  ): Promise<FacilityAdmin | null> {
    const result = await this.service.facilityAdmin(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FacilityAdmin)
  async createFacilityAdmin(
    @graphql.Args() args: CreateFacilityAdminArgs
  ): Promise<FacilityAdmin> {
    return await this.service.createFacilityAdmin({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => FacilityAdmin)
  async updateFacilityAdmin(
    @graphql.Args() args: UpdateFacilityAdminArgs
  ): Promise<FacilityAdmin | null> {
    try {
      return await this.service.updateFacilityAdmin({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => FacilityAdmin)
  async deleteFacilityAdmin(
    @graphql.Args() args: DeleteFacilityAdminArgs
  ): Promise<FacilityAdmin | null> {
    try {
      return await this.service.deleteFacilityAdmin(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Facility], { name: "facilities" })
  async findFacilities(
    @graphql.Parent() parent: FacilityAdmin,
    @graphql.Args() args: FacilityFindManyArgs
  ): Promise<Facility[]> {
    const results = await this.service.findFacilities(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
