/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Accountant as PrismaAccountant,
  Facility as PrismaFacility,
} from "@prisma/client";

export class AccountantServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AccountantCountArgs, "select">
  ): Promise<number> {
    return this.prisma.accountant.count(args);
  }

  async accountants(
    args: Prisma.AccountantFindManyArgs
  ): Promise<PrismaAccountant[]> {
    return this.prisma.accountant.findMany(args);
  }
  async accountant(
    args: Prisma.AccountantFindUniqueArgs
  ): Promise<PrismaAccountant | null> {
    return this.prisma.accountant.findUnique(args);
  }
  async createAccountant(
    args: Prisma.AccountantCreateArgs
  ): Promise<PrismaAccountant> {
    return this.prisma.accountant.create(args);
  }
  async updateAccountant(
    args: Prisma.AccountantUpdateArgs
  ): Promise<PrismaAccountant> {
    return this.prisma.accountant.update(args);
  }
  async deleteAccountant(
    args: Prisma.AccountantDeleteArgs
  ): Promise<PrismaAccountant> {
    return this.prisma.accountant.delete(args);
  }

  async findFacilities(
    parentId: string,
    args: Prisma.FacilityFindManyArgs
  ): Promise<PrismaFacility[]> {
    return this.prisma.accountant
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .facilities(args);
  }
}
