/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AccountantWhereUniqueInput } from "../../accountant/base/AccountantWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
} from "class-validator";
import { Type } from "class-transformer";
import { DoctorWhereUniqueInput } from "../../doctor/base/DoctorWhereUniqueInput";
import { FacilityAdminWhereUniqueInput } from "../../facilityAdmin/base/FacilityAdminWhereUniqueInput";

@InputType()
class FacilityUpdateInput {
  @ApiProperty({
    required: false,
    type: () => AccountantWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AccountantWhereUniqueInput)
  @IsOptional()
  @Field(() => AccountantWhereUniqueInput, {
    nullable: true,
  })
  accountant?: AccountantWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  contactNumber?: string | null;

  @ApiProperty({
    required: false,
    type: () => DoctorWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DoctorWhereUniqueInput)
  @IsOptional()
  @Field(() => DoctorWhereUniqueInput, {
    nullable: true,
  })
  doctor?: DoctorWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => FacilityAdminWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => FacilityAdminWhereUniqueInput)
  @IsOptional()
  @Field(() => FacilityAdminWhereUniqueInput, {
    nullable: true,
  })
  facilityAdmin?: FacilityAdminWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  typeField?: string | null;
}

export { FacilityUpdateInput as FacilityUpdateInput };
