/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SuperAdminService } from "../superAdmin.service";
import { SuperAdminCreateInput } from "./SuperAdminCreateInput";
import { SuperAdmin } from "./SuperAdmin";
import { SuperAdminFindManyArgs } from "./SuperAdminFindManyArgs";
import { SuperAdminWhereUniqueInput } from "./SuperAdminWhereUniqueInput";
import { SuperAdminUpdateInput } from "./SuperAdminUpdateInput";

export class SuperAdminControllerBase {
  constructor(protected readonly service: SuperAdminService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: SuperAdmin })
  async createSuperAdmin(
    @common.Body() data: SuperAdminCreateInput
  ): Promise<SuperAdmin> {
    return await this.service.createSuperAdmin({
      data: data,
      select: {
        createdAt: true,
        email: true,
        employeeId: true,
        firstName: true,
        id: true,
        lastName: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [SuperAdmin] })
  @ApiNestedQuery(SuperAdminFindManyArgs)
  async superAdmins(@common.Req() request: Request): Promise<SuperAdmin[]> {
    const args = plainToClass(SuperAdminFindManyArgs, request.query);
    return this.service.superAdmins({
      ...args,
      select: {
        createdAt: true,
        email: true,
        employeeId: true,
        firstName: true,
        id: true,
        lastName: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: SuperAdmin })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async superAdmin(
    @common.Param() params: SuperAdminWhereUniqueInput
  ): Promise<SuperAdmin | null> {
    const result = await this.service.superAdmin({
      where: params,
      select: {
        createdAt: true,
        email: true,
        employeeId: true,
        firstName: true,
        id: true,
        lastName: true,
        phoneNumber: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: SuperAdmin })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSuperAdmin(
    @common.Param() params: SuperAdminWhereUniqueInput,
    @common.Body() data: SuperAdminUpdateInput
  ): Promise<SuperAdmin | null> {
    try {
      return await this.service.updateSuperAdmin({
        where: params,
        data: data,
        select: {
          createdAt: true,
          email: true,
          employeeId: true,
          firstName: true,
          id: true,
          lastName: true,
          phoneNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: SuperAdmin })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSuperAdmin(
    @common.Param() params: SuperAdminWhereUniqueInput
  ): Promise<SuperAdmin | null> {
    try {
      return await this.service.deleteSuperAdmin({
        where: params,
        select: {
          createdAt: true,
          email: true,
          employeeId: true,
          firstName: true,
          id: true,
          lastName: true,
          phoneNumber: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
