/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { SuperAdmin } from "./SuperAdmin";
import { SuperAdminCountArgs } from "./SuperAdminCountArgs";
import { SuperAdminFindManyArgs } from "./SuperAdminFindManyArgs";
import { SuperAdminFindUniqueArgs } from "./SuperAdminFindUniqueArgs";
import { CreateSuperAdminArgs } from "./CreateSuperAdminArgs";
import { UpdateSuperAdminArgs } from "./UpdateSuperAdminArgs";
import { DeleteSuperAdminArgs } from "./DeleteSuperAdminArgs";
import { SuperAdminService } from "../superAdmin.service";
@graphql.Resolver(() => SuperAdmin)
export class SuperAdminResolverBase {
  constructor(protected readonly service: SuperAdminService) {}

  async _superAdminsMeta(
    @graphql.Args() args: SuperAdminCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [SuperAdmin])
  async superAdmins(
    @graphql.Args() args: SuperAdminFindManyArgs
  ): Promise<SuperAdmin[]> {
    return this.service.superAdmins(args);
  }

  @graphql.Query(() => SuperAdmin, { nullable: true })
  async superAdmin(
    @graphql.Args() args: SuperAdminFindUniqueArgs
  ): Promise<SuperAdmin | null> {
    const result = await this.service.superAdmin(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => SuperAdmin)
  async createSuperAdmin(
    @graphql.Args() args: CreateSuperAdminArgs
  ): Promise<SuperAdmin> {
    return await this.service.createSuperAdmin({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => SuperAdmin)
  async updateSuperAdmin(
    @graphql.Args() args: UpdateSuperAdminArgs
  ): Promise<SuperAdmin | null> {
    try {
      return await this.service.updateSuperAdmin({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => SuperAdmin)
  async deleteSuperAdmin(
    @graphql.Args() args: DeleteSuperAdminArgs
  ): Promise<SuperAdmin | null> {
    try {
      return await this.service.deleteSuperAdmin(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
