/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, SuperAdmin as PrismaSuperAdmin } from "@prisma/client";

export class SuperAdminServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SuperAdminCountArgs, "select">
  ): Promise<number> {
    return this.prisma.superAdmin.count(args);
  }

  async superAdmins(
    args: Prisma.SuperAdminFindManyArgs
  ): Promise<PrismaSuperAdmin[]> {
    return this.prisma.superAdmin.findMany(args);
  }
  async superAdmin(
    args: Prisma.SuperAdminFindUniqueArgs
  ): Promise<PrismaSuperAdmin | null> {
    return this.prisma.superAdmin.findUnique(args);
  }
  async createSuperAdmin(
    args: Prisma.SuperAdminCreateArgs
  ): Promise<PrismaSuperAdmin> {
    return this.prisma.superAdmin.create(args);
  }
  async updateSuperAdmin(
    args: Prisma.SuperAdminUpdateArgs
  ): Promise<PrismaSuperAdmin> {
    return this.prisma.superAdmin.update(args);
  }
  async deleteSuperAdmin(
    args: Prisma.SuperAdminDeleteArgs
  ): Promise<PrismaSuperAdmin> {
    return this.prisma.superAdmin.delete(args);
  }
}
